"""Abstract base classes for TradingLab components.

These define the interfaces that all strategy, regime, and risk
components must implement. The actual implementations are private.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Optional


class Regime(Enum):
    """Market regime classification."""
    BULL = "BULL"
    NEUTRAAL = "NEUTRAAL"
    BEAR = "BEAR"
    TURBULENT = "TURBULENT"


class Side(Enum):
    """Trade side."""
    BUY = "BUY"
    SELL = "SELL"


class InstrumentType(Enum):
    """Instrument classification for cost calculation."""
    INDIVIDUAL_STOCK = "INDIVIDUAL"      # 0.35% TOB
    SECTOR_ETF = "SECTOR_ETF"            # 0.12% TOB
    LEVERAGED_ETP = "LEVERAGED"          # 0.12% TOB
    CRYPTO = "CRYPTO"                     # 0% TOB


@dataclass
class Signal:
    """A trading signal generated by the strategy engine."""
    ticker: str
    side: Side
    score: float
    conviction: int  # 0-3
    regime: Regime
    instrument_type: InstrumentType
    sizing_pct: float
    timestamp: datetime
    signals: list[str]  # ["TECHNISCH", "VOLUME", "MARKT"]
    metadata: dict = None


@dataclass
class Position:
    """An open position in the portfolio."""
    ticker: str
    entry_price: float
    quantity: float
    entry_date: datetime
    instrument_type: InstrumentType
    conviction: int
    take_profit_pct: float
    trailing_stop_pct: float
    break_even_active: bool = False
    peak_price: float = 0.0
    original_signal: str = ""  # ticker that triggered the entry


@dataclass
class TradeResult:
    """Result of a closed trade."""
    ticker: str
    side: Side
    entry_price: float
    exit_price: float
    pnl_pct: float
    pnl_eur: float
    fees: float
    tob: float
    reason: str
    hold_days: int
    conviction: int
    instrument_type: InstrumentType


class RegimeDetector(ABC):
    """Abstract regime detector. Implementations use different
    indicators for equities vs crypto."""

    @abstractmethod
    def detect(self) -> dict:
        """Detect current market regime.

        Returns:
            {
                "regime": Regime,
                "confidence": float,
                "indicators": dict
            }
        """
        ...

    @abstractmethod
    def is_safe_to_trade(self) -> bool:
        """Check if market conditions allow trading."""
        ...


class ConvictionEngine(ABC):
    """Abstract conviction calculator. Counts independent
    confirmations for a trade signal."""

    @abstractmethod
    def calculate(self, ticker: str, indicators: dict,
                  regime: Regime) -> tuple[int, list[str]]:
        """Calculate conviction score (0-3) and list of signals.

        Returns:
            (conviction: int, signals: ["TECHNISCH", "VOLUME", "MARKT"])
        """
        ...


class InstrumentSelector(ABC):
    """Abstract instrument selector. Maps conviction level
    to the optimal instrument (ETF vs individual stock)."""

    @abstractmethod
    def select(self, ticker: str, conviction: int,
               sector: str) -> dict:
        """Select instrument based on conviction.

        Returns:
            {
                "ticker": str,        # IITU or AAOI
                "is_etf": bool,
                "tob_pct": float,     # 0.0012 or 0.0035
                "exchange": str,
                "original_signal": str
            }
        """
        ...


class ExitManager(ABC):
    """Abstract exit manager. Handles TP, trailing stop,
    break-even, max hold, and technical exits."""

    @abstractmethod
    def evaluate(self, position: Position,
                 current_price: float) -> Optional[dict]:
        """Evaluate if a position should be closed.

        Returns None if no exit, or:
            {
                "reason": str,
                "exit_price": float,
                "pnl_pct": float
            }
        """
        ...


class RiskManager(ABC):
    """Abstract risk manager. Portfolio-level risk controls."""

    @abstractmethod
    def check_entry(self, signal: Signal,
                    portfolio: list[Position]) -> bool:
        """Check if a new entry is allowed given current portfolio."""
        ...

    @abstractmethod
    def check_circuit_breaker(self,
                               daily_pnl: float) -> bool:
        """Check if circuit breaker should activate."""
        ...


class CostCalculator:
    """Transaction cost calculator for Belgian investors.

    TOB (Taks op Beursverrichtingen):
    - Individual stocks: 0.35% per transaction, max €1,600
    - ETFs (non-Belgian): 0.12% per transaction, max €1,300
    - Accumulating Belgian funds: 1.32% per transaction, max €4,000
    - Crypto, options, futures: 0%

    Source: FOD Financiën circulaire 2026/C/42
    """

    TOB_RATES = {
        InstrumentType.INDIVIDUAL_STOCK: (0.0035, 1600),
        InstrumentType.SECTOR_ETF: (0.0012, 1300),
        InstrumentType.LEVERAGED_ETP: (0.0012, 1300),
        InstrumentType.CRYPTO: (0.0, 0),
    }

    IBKR_TIERED_PER_SHARE = 0.0035  # USD
    IBKR_MIN_PER_ORDER = 0.35       # USD
    FX_CONVERSION_PCT = 0.0003      # 0.03%

    @classmethod
    def calculate_tob(cls, instrument_type: InstrumentType,
                      trade_value_eur: float) -> float:
        """Calculate Belgian transaction tax."""
        rate, cap = cls.TOB_RATES[instrument_type]
        return min(trade_value_eur * rate, cap)

    @classmethod
    def calculate_commission(cls, shares: int) -> float:
        """Calculate IBKR tiered commission in USD."""
        return max(shares * cls.IBKR_TIERED_PER_SHARE,
                   cls.IBKR_MIN_PER_ORDER)

    @classmethod
    def calculate_total_cost(cls, instrument_type: InstrumentType,
                              trade_value_eur: float,
                              shares: int,
                              is_usd: bool = True) -> dict:
        """Calculate all transaction costs."""
        tob = cls.calculate_tob(instrument_type, trade_value_eur)
        commission = cls.calculate_commission(shares) * 0.92  # USD→EUR
        fx = trade_value_eur * cls.FX_CONVERSION_PCT if is_usd else 0

        return {
            "tob": round(tob, 4),
            "commission": round(commission, 4),
            "fx": round(fx, 4),
            "total": round(tob + commission + fx, 4)
        }
